### ISSUE TITLE
Generation fails silently for deeply nested collections.

### ISSUE THREAD

**Issue by LadyDascalie** [thedevsaddam/docgen#1]
I currently have a pretty large collection (600+ requests), neatly organized in sub folders, nested between 3 for 5 deep.

When trying to build or view the collection, the generation says that it's successful, but the nested trees end up empty:
![like so](https://i.imgur.com/2mkyFAe.png)

Unfortunately, I cannot share the postman collection, but if necessary, I may be able to reproduce it in a contrived manner.

**Comment by thedevsaddam** [comment]
@LadyDascalie  `docgen v1.0` does not support nested collections. Need a pull request :)

```
$ docgen version
Docgen version: v0.1
Support postman collection version > 2.1
Note: Does not support postman sub directory collection
```

**Comment by LadyDascalie** [comment]
That's my bad!

In that case I might give that feature a shot. Feel free to close this issue!

**Comment by sagar290** [comment]
the same problem arises again. I am using v3.0.0
![image](https://user-images.githubusercontent.com/7631656/107995633-d9240d80-7008-11eb-8f76-b0df901c4151.png)
