### ISSUE TITLE
JSON pretty print problem with raw text request body

### ISSUE THREAD

**Issue by FabienSailliet** [thedevsaddam/docgen#12]
I have a Postman project ([Test collection.postman_collection.txt](https://github.com/thedevsaddam/docgen/files/3112565/Test.collection.postman_collection.txt)) which contains two GET requests, returning JSON-parsed informations, and a PUT request, which get informations as raw text in the request body.

When loading the docgen-generated HTML file, the page seems to try to pretty-print the body raw text, as a JSON string, as you can see with this exception:

```
"SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLSpanElement.<anonymous> (http://localhost:8001/:384:22)
    at Function.each (http://localhost:8001/:344:2881)
    at n.fn.init.each (http://localhost:8001/:344:846)
    at HTMLDocument.<anonymous> (http://localhost:8001/:370:32)
    at i (http://localhost:8001/:344:27449)
    at Object.fireWith [as resolveWith] (http://localhost:8001/:344:28213)
    at Function.ready (http://localhost:8001/:344:30006)
    at HTMLDocument.K (http://localhost:8001/:344:30368)"
```

With the browser debugger, we can see the raw text failed to be pretty-printed:

![image](https://user-images.githubusercontent.com/49949519/56665572-94e4b200-66aa-11e9-8dff-c080cc85e908.png)

This gives the following:

![image](https://user-images.githubusercontent.com/49949519/56665875-2d7b3200-66ab-11e9-9558-8f8e5b71e26c.png)

![image](https://user-images.githubusercontent.com/49949519/56666050-7df28f80-66ab-11e9-8dd9-b066a1665966.png)

![image](https://user-images.githubusercontent.com/49949519/56666102-95317d00-66ab-11e9-83cc-75625301ea19.png)

As you can see, the PUT request body isn't display, and the JSON strings after this request are not pretty-printed.

**Comment by Enrico204** [comment]
Hi @FabienSailliet ! Can you provide a simple Postman collection export to try with and fix? Thanks :-)

**Comment by FabienSailliet** [comment]
I do so in my first message.

**Comment by Enrico204** [comment]
Sorry I missed that link! I'll try ASAP and see if I can provide a fix :-)

**Comment by FabienSailliet** [comment]
Ok, thanks

**Comment by Enrico204** [comment]
I think that I found the issue. Can you please confirm that the Markdown version is showing the raw PUT request correctly?

**Comment by FabienSailliet** [comment]
Yes, it seems to do so.

**Comment by Enrico204** [comment]
Perfect! So I made the pull request, let's wait for @thedevsaddam to merge it :-)
