### ISSUE TITLE
The requests in the default folder are in the reverse order

### ISSUE THREAD

**Issue by FabienSailliet** [thedevsaddam/docgen#13]
If we generate a Markdown or HTML file from a Postman collection, the requests directly in the collection (outside any subfolder) are reversed.

For example, with the following collection:

![image](https://user-images.githubusercontent.com/49949519/56744373-a8f6e500-6778-11e9-964e-b2c80608cba6.png)

```JSON
{
	"info": {
		"_postman_id": "72a750d2-5658-4e2f-a475-3317b4c7ec73",
		"name": "Test collection (requests order bug)",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "first",
			"request": {
				"method": "GET",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": ""
				},
				"url": {
					"raw": ""
				}
			},
			"response": []
		},
		{
			"name": "second",
			"request": {
				"method": "GET",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": ""
				},
				"url": {
					"raw": ""
				}
			},
			"response": []
		},
		{
			"name": "third",
			"request": {
				"method": "GET",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": ""
				},
				"url": {
					"raw": ""
				}
			},
			"response": []
		}
	]
}
```

We get the following html:

![image](https://user-images.githubusercontent.com/49949519/56744315-88c72600-6778-11e9-89b3-d7388359e296.png)

**Comment by tahayk** [comment]
still having same issue, any idea how to solve this ?

**Comment by FabienSailliet** [comment]
Same under Linux with v2.3 and the same collection.

I tried to quickly look over the code, but I don't know Go, so I will not be really useful, sorry.

**Comment by Enrico204** [comment]
The default implementation of JSON decoder in Go is JSON-standard compliant, but Postman (or maybe the library that they're using) is not.

In short: Postman expect that writing a sorted JSON array to file is sufficient to maintain the order that users set in the UI. This is not correct, as the JSON standard says that JSON arrays order can be ignored by JSON parsers, as Go does.
There are some 3rd party libraries that tries to preserve the order, I'll try to integrate one of those

**Comment by Enrico204** [comment]
I found the code part that does the sorting. I'll create a pull request to add a command line switch to enable/disable collections sort :-)

**Comment by Enrico204** [comment]
@FabienSailliet can you check if this problem is fixed in the latest version? Thanks :-)

**Comment by akiselev1** [comment]
@Enrico204 I checked - the sorting problem is still there today. -s switch is visible in help and accepted. But it does not change the reverse sort order. It is reproducible with the original test json posted by @FabienSailliet 
Docgen version: v2.3

**Comment by abhijitnathwani** [comment]
@Enrico204 @thedevsaddam  This problem is still persistent. Do we have any solution for this?

**Comment by thedevsaddam** [comment]
@abhijitnathwani , Hopefully, it will be solved by next release [v3.0.0]. There will be major changes in UI.

In the case of `directory` or `requests` ordering:
- The default will be as it shows in postman
- `-s` flag will sort the items (directory, requests) in lexical order

**Comment by thedevsaddam** [comment]
Please use the latest `v3.0.0-rc`

```sh
curl https://raw.githubusercontent.com/thedevsaddam/docgen/v3/install.sh -o install.sh && sudo chmod +x install.sh && sudo ./install.sh

```

> I'm closing the issue. If anything goes wrong, please feel free to create an issue or reopen

**Comment by abhijitnathwani** [comment]
Thanks @thedevsaddam . The `-s` flag sorts lexically now.

However, the default behavior is still ordering in reverse. We can verify that by checking the sequence in `collection.json` and the generated output. Should I open an issue to track that?

**Comment by thedevsaddam** [comment]
The default order is using parent directories in order but the children are going out of order

<img width="1236" alt="Screenshot 2020-05-14 19 16 59" src="https://user-images.githubusercontent.com/9676798/81939038-a0897a80-9617-11ea-952c-e3c14a2f1842.png">

> Note: Probably I'll need a PR for that :( 

**Update: Removed the `s` flag, from now on the collections will be in lexical order by default**

**Comment by mnich0ls** [comment]
I'm also still seeing sorting not following the same order of the requests in the collection by default: 
<img width="696" alt="Screen Shot 2020-05-21 at 4 55 30 PM" src="https://user-images.githubusercontent.com/3977170/82617232-4c851580-9b84-11ea-9769-219f275276ef.png">

I used the Mac binary 3.0.0-rc2 - https://github.com/thedevsaddam/docgen-bin/blob/master/latest/mac_amd64

**Comment by thedevsaddam** [comment]
The collections are ordered alphabetically,
a-z etc

**Comment by pachylover** [comment]
If requests has group, it works.
But it doesn't grouped, it's ordered as reverse
