### ISSUE TITLE
Cannot build for Windows

### ISSUE THREAD

**Issue by clairestreb** [thedevsaddam/docgen#21]
I want to run docgen on Windows.  README.md says to get the binary, but it is not up-to-date with the master, and I want to get the latest checkins.

I ran the installation command per README.md, but it gives an error:

```
C:\Users\cstreb\go\src>go get -u github.com/thedevsaddam/docgen
# github.com/thedevsaddam/docgen
github.com\thedevsaddam\docgen\funcmap.go:17:13: undefined: AssetFS
```

I downloaded and unzipped the zip file to a different folder, opened a cmd window there, and tried this which fails with the same error:

```
C:\Users\cstreb\go\src\docgen-2-20190809>go build -o ..\docgen.exe
# docgen-2-20190809
.\funcmap.go:17:13: undefined: AssetFS
```

I also went up a level and tried the following, but still get the same error:

```
C:\Users\cstreb\go\src>go build docgen-2-20190809
# docgen-2-20190809
docgen-2-20190809\funcmap.go:17:13: undefined: AssetFS
```

Sorry, I do not know go.  Am I missing something?

**Comment by clairestreb** [comment]
Any help / reply please?

**Comment by Enrico204** [comment]
Hi! I'm facing the same problem by downloading with `go get`. I'll check and investigate :-)

**Comment by Enrico204** [comment]
Ok apparently `go generate` is not usable with plain `go get`. You can execute `go generate` inside the downloaded source folder before your `go build` to generate a Windows build.

I made a pull request which fixes this issue :-)
