### ISSUE TITLE
[FeatureRequest] Inject style.css

### ISSUE THREAD

**Issue by ikrum** [thedevsaddam/docgen#23]
# Background
I wanted to run the the built in server. But I need to add 10 lines of css code and adjust the appearances. I would be nice to have such feature that would add additional css into the server or maybe in the build as well.

## Current Command
```docgen server -f input-postman-collection.json -p 8000```

## Proposed Command
```docgen server -f input-postman-collection.json -c style.css -p 8000```

**Comment by Anondo** [comment]
On it, sending you a PR with this feature @thedevsaddam
