### ISSUE TITLE
Error: Unknown command: docgen

### ISSUE THREAD

**Issue by ma-za-kpe** [thedevsaddam/docgen#26]
When i try to build the json file from postman on UBUNTU 18.04, using this ==> brew docgen build -i DevCamperAPI.json -o index.html
It throws this ==> Error: Unknown command: docgen

Please help.

**Comment by backspacerhino** [comment]
Have you tried **./docgen** instead of docgen (...)?

**Comment by jasonbunnell** [comment]
I am having the same problem on Ubuntu 18.04.  Installed docgen using homebrew.  I tried upgrading and got:

> thedevsaddam/cli/docgen 2.3 already installed

Any ideas?

**Comment by thedevsaddam** [comment]
Guys, the problem was in the binary. Because the binary was only for mac, that time Linux did not support brew.

This will be fixed soon. You can install the binary manually, it will work.

> Sorry, for delayed reply :(

**Comment by thedevsaddam** [comment]
Please use the latest `v3.0.0-rc`

```sh
curl https://raw.githubusercontent.com/thedevsaddam/docgen/v3/install.sh -o install.sh && sudo chmod +x install.sh && sudo ./install.sh

```

> I'm closing the issue. If anything goes wrong, please feel free to create an issue or reopen
