### ISSUE TITLE
Response examples do not show request body

### ISSUE THREAD

**Issue by mnich0ls** [thedevsaddam/docgen#28]
First off, this is a great little tool. I love it!

The "examples" for a request do not include the request body for each response example. I see how I can work around it by creating a new top-level request for each example, but it seems to clutter the interface in Postman by having to create a lot of requests for each API, rather than using the examples concept that seems to solve that problem quite nicely.  I'm happy to reorganize my requests and APIs, but I'm curious if there's a way to have an optional flag to also include the request body for each example? 

My API folders and routes in Postman:
![image](https://user-images.githubusercontent.com/3977170/81245569-27ac7200-8fca-11ea-9774-70887344eeb0.png)

An example request/response in Postman:
![image](https://user-images.githubusercontent.com/3977170/81245702-8a057280-8fca-11ea-96e2-255e44b5672a.png)

The resulting markdown without the request body:
![image](https://user-images.githubusercontent.com/3977170/81245717-95589e00-8fca-11ea-8bd6-78d09657e110.png)

Thanks!

**Comment by thedevsaddam** [comment]
Assuming you are talking about including the request body.

The documentation should add the request body. Please check the input JSON file.

**Input:**

<img width="922" alt="Screenshot 2020-05-07 10 31 09" src="https://user-images.githubusercontent.com/9676798/81254858-10af6380-904e-11ea-9aec-c766c9d6437c.png">

**Markdown documentation:**

<img width="1072" alt="Screenshot 2020-05-07 10 31 59" src="https://user-images.githubusercontent.com/9676798/81254842-0ab98280-904e-11ea-9b67-c5a418a0b81f.png">

**HTML documentation:**

<img width="1020" alt="Screenshot 2020-05-07 10 31 26" src="https://user-images.githubusercontent.com/9676798/81254855-0e4d0980-904e-11ea-845c-4c92cfd4be12.png">

Unfortunately, I could not simulate the response, but it will work fine.

> Docgen version: v2.3
> Support postman collection version > 2.1

> Thanks for the appreciation!

**Comment by mnich0ls** [comment]
I believe what you demonstrated is that the request body is shown for the “main” request, but they are not shown for the “examples” for the request. I can send more screen shots later this morning when I’m at my computer, if that helps. 

I also need to get more familiar with better ways of organizing my collection.  I’m using Postman “requests” to define specific routes of my API, rather than define many requests with different examples for the same route, if that makes sense..

**Comment by mnich0ls** [comment]
The examples for a request: 
![image](https://user-images.githubusercontent.com/3977170/81343141-44e44d80-9069-11ea-8f91-93a735a6487d.png)
![image](https://user-images.githubusercontent.com/3977170/81343175-53cb0000-9069-11ea-96cc-24de00dbee4e.png)

Examples show up in the documentation as "responses" not as "examples" as they're named in Postman.

**Comment by thedevsaddam** [comment]
Please use the latest `v3.0.0-rc`

```sh
curl https://raw.githubusercontent.com/thedevsaddam/docgen/v3/install.sh -o install.sh && sudo chmod +x install.sh && sudo ./install.sh

```

> Don't forget to provide feedback and close the opened issue.

**Comment by mnich0ls** [comment]
I will try this today. Thank you!

**Comment by mnich0ls** [comment]
This is great @thedevsaddam. I have some other suggestions, but I will put them in a new issue.
