### ISSUE TITLE
clicking to show API detail work wrong when Chinese included!

### ISSUE THREAD

**Issue by blukhand** [thedevsaddam/docgen#3]
great job !
it work good with postman collection 2.1. 
i found it may not support postman collection1 and collection 2 .
and i found a problem. when the api info included Chinese word, the html file work wrong. it show the first api detail no matter which api you click in that list. 
do you have the plan to add Chinese support? i hope i can help this. 
thank you again for your job.

**Comment by blukhand** [comment]
> @blukhand Can you send me a sample postman collection containing Chinese language.

hi, the collection containing Chinese language and the html file generated  have been send to your gmail mailbox. hope that can help. 

if not receive or you had other question. please contact me. 
thank u

**Comment by thedevsaddam** [comment]
> > @blukhand Can you send me a sample postman collection containing Chinese language.
> 
> i think i found the cause. in the function snake. it delete all characters out of [A-Za-z0-9]. so all chinese name will be turn to empty string. the id of all collapsed element in the page will be the same. so the collapse.js work wrong.
> 
> i modify the snake function locally and make this support Chinese and other language.
> 
> can i push this little change?

Thats great! You can send PR against `Dev` branch
