### ISSUE TITLE
Feature Request: environment variables

### ISSUE THREAD

**Issue by gang83211** [thedevsaddam/docgen#31]
Postman can use `{{ }}` to set environment variables,
For example: I can turn `{{url}}/dosomethingapi` into `https://example.domain/dosomethingapi`,
But the current version does not support this feature, I hope to add this feature, it can use `docgen build -i input-postman-collection.json -o ~/Downloads/doc.html -e ~/Downloads/postman_environment.json`

**Comment by thedevsaddam** [comment]
Environment variables support implemented in #33
