### ISSUE TITLE
Weird Behavior with <> in Response Body

### ISSUE THREAD

**Issue by graykathy** [thedevsaddam/docgen#32]
When Postman exports a collection to json, it includes the response objects. When that is run through DocGen, if the response body includes the characters < and >, it is returning some weird behavior.  For instance:
![image](https://user-images.githubusercontent.com/65370318/82064161-41f8e680-9681-11ea-9c6e-eb8904dbe58f.png)
As you can see, it added < /integer >< /integer > to the end.  
If the response body includes < object >, it kills the rest of the document:
![image](https://user-images.githubusercontent.com/65370318/82064319-753b7580-9681-11ea-8ef5-d90a61d016f3.png)
Here, it dropped the word "Body", and then attached the remainder of the document to the end of the "Body" section.  If I manually replace < object > with < string >, then it returns to the behavior listed above.

**Comment by thedevsaddam** [comment]
Can you please provide an example postman collection file that can generate the behavior?

> Please provide the docgen version as well

**Comment by graykathy** [comment]
Attached are a sample collection, and the html that docgen created.  I used the command line "docgen build -i postman_collection.json -o index.html -s"

[docgenTest.zip](https://github.com/thedevsaddam/docgen/files/4645242/docgenTest.zip)

**Comment by thedevsaddam** [comment]
The latest version `v3.0.0-rc2` solved the issue.

```sh
 curl https://raw.githubusercontent.com/thedevsaddam/docgen/v3/install.sh -o install.sh && sudo chmod +x install.sh && sudo ./install.sh
```

**Comment by graykathy** [comment]
Thank you! I downloaded the latest version, but it appears the –s flag is no longer working.

**Comment by graykathy** [comment]
Also, when I remove the –s, and run the command “docgen build -i postman_collection.json -o index.html”, I get the following error now(where it was working before):
2020/05/19 09:49:37 parsing json filejson: cannot unmarshal object into Go struct field Field.item.item.item.item.response.originalRequest.body.formdata.description of type string
