### ISSUE TITLE
Windows: docgen' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by louagej** [thedevsaddam/docgen#37]
Hi,

I installed the latest windows_amd64.exe as explained in the readme.

- Also added the binary as env. variable

- Rebooted pc

But when trying to run `docgen server -f API.postman_collection.json -p 8000`, I receive the error message:

`'docgen' is not recognized as an internal or external command,
operable program or batch file.`

![image](https://user-images.githubusercontent.com/7229592/87587338-3c039e00-c6e2-11ea-91eb-18b81af37dc5.png)

Any idea if there are extra steps to perform?

Kind regards,
Job

**Comment by vladi-strilets** [comment]
Use the name of the binary file you have downloaded, for example: 
```
$ windows_amd64 build -i API.postman_collection.json -o index.html
```

**Comment by louagej** [comment]
> Use the name of the binary file you have downloaded, for example:
> 
> ```
> $ windows_amd64 build -i API.postman_collection.json -o index.html
> ```

@vladi-strilets ,

thanks, that did the job :relieved:
If anyone has the same issue, below the powershell command:
> ```Powershell
> $PostmanCollectionPath = "C:\Users\<<Username>>\Documentation\API.postman_collection.json"
> $PostmanDocumentationPath = "C:\Users\<<Username>>\Documentation\API.postman_collection.html"
> windows_amd64 build -i $PostmanCollectionPath -o $PostmanDocumentationPath
> ```

Output, see below:

![2020-07-22 10_26_48](https://user-images.githubusercontent.com/7229592/88153803-30decf80-cc06-11ea-83a5-53fc93a377e4.png)

**Comment by ionicstuff** [comment]
> Use the name of the binary file you have downloaded, for example:
> 
> ```
> $ windows_amd64 build -i API.postman_collection.json -o index.html
> ```

Thank you very much, I was struggling since this morning and your reply actually helped. Best wishes.
