### ISSUE TITLE
"Refused to execute inline script..." error in chrome console.

### ISSUE THREAD

**Issue by azakero** [thedevsaddam/docgen#40]
Hello thedevsaddam,

I'm having a weird issue after generating an index.html file for my API. If I run it directly then it works perfectly fine without any errors but if I run it in my NodeJS-Express app (as shown in an udemy course) it throws an error in the dev console after clicking on the collapsed state of the endpoints. What could be the issue? 
![1](https://user-images.githubusercontent.com/49979539/92583519-3b3b5280-f2b4-11ea-86a6-eb72ec9d4925.jpg)

**Comment by afhslll** [comment]
How did you solve this? I encountered same issue.

**Comment by azakero** [comment]
> How did you solve this? I encountered same issue.

Ummm, I don't exactly remember but I guess I did something to the anchor links in the html file that is generated. I think I changed the host in the anchor links or may be deleted it. You can give it a try.
