### ISSUE TITLE
Do not sort the collections in lexical order by default.

### ISSUE THREAD

**Issue by KoenDG** [thedevsaddam/docgen#54]
I noticed that the list ordering differs from Postman. Postman respects the order in which you wrote things down.

If I have a list that says:

 1. Login.json
 2. Validate.json
 3. GetUserInfo.json

docgen will generate this to be in order: 3-1-2.

There is, however, a clear reason I put those documents in that specific order. It should not be changed.

Looking at the code: 
https://github.com/thedevsaddam/docgen/blob/517f6632a913db19f676d79f927dc9c0370e8592/collection/collection.go#L112

and

https://github.com/thedevsaddam/docgen/blob/517f6632a913db19f676d79f927dc9c0370e8592/collection/collection.go#L167

This behavior is hardcoded and I think it should configurable.

**Comment by thedevsaddam** [comment]
This [release](https://github.com/thedevsaddam/docgen/releases/tag/v3.2.0) solved the issue.
