### ISSUE TITLE
Links to markdown anchors with parenthesis not working

### ISSUE THREAD

**Issue by mnich0ls** [thedevsaddam/docgen#62]
The links generated at the top of a markdown document that link to each request and request example, don't seem to format the header ID the same way markdown converters do. e.g. they do not strip out parenthesis or "="

[My Header (var=true)](#my-header-(var=true))

# My Header (var=true)

I've tested the generated markdown in Gitlab and a markdown plugin for Chrome and see the same results. I'm not sure if Github generates anchor IDs differently (I added the example above to check). Here's the Gitlab documentation showing how IDs for headers with parenthesis are generated: https://docs.gitlab.com/ee/user/markdown.html#header-ids-and-links

**Comment by thedevsaddam** [comment]
@mnich0ls Thanks for fixing the issue 👍

**Comment by mnich0ls** [comment]
No problem. Thanks for merging.
