### ISSUE TITLE
Path Variables are not shown in documentation

### ISSUE THREAD

**Issue by ElliotReeve** [thedevsaddam/docgen#9]
If you add a path variable into the URL by adding :variable then describe it in Postman it is not shown in the documentation.

![Screenshot 2019-04-01 at 16 20 21](https://user-images.githubusercontent.com/4366096/55339178-16756580-549a-11e9-9fe5-2b5ad31c284f.png)

By adding this into Postman the JSON has an additional "path" parameter which maps to a "key" inside the "variable" array:

```json
  "url": {
    "raw": "{{url}}/logs/:schedule_id",
    "host": [
      "{{url}}"
    ],
    "path": [
      "logs",
      ":schedule_id"
    ],
    "variable": [
      {
        "key": "schedule_id",
        "value": "2",
        "description": "ID of the Schedule"
      }
    ]
  }
```
Is it possible to get this added in?

Thanks

**Comment by thedevsaddam** [comment]
Added in v2.3, please download the new binary

**Comment by FabienSailliet** [comment]
Using the v2.3, I have the same problem.

Postman collection:

```json
{
	"info": {
		"_postman_id": "7163edf0-0edd-44d6-bf9b-25645ba25d51",
		"name": "Params test collection",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Get something",
			"request": {
				"method": "GET",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": ""
				},
				"url": {
					"raw": "{{URL}}/:what",
					"host": [
						"{{URL}}"
					],
					"path": [
						":what"
					],
					"variable": [
						{
							"key": "what",
							"value": "",
							"description": "The thing to get"
						}
					]
				},
				"description": "Get whatever you want."
			},
			"response": []
		}
	]
}
```

Result:

![image](https://user-images.githubusercontent.com/49949519/56667771-bcd61480-66ae-11e9-9bf6-06db6b0034f7.png)
